[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
fs_permissions = [
    {access = "read", path = "./files/in"},
    {access = "read-write", path = "./files/out"}
]


[rpc_endpoints]
avalanche = "https://api.avax.network/ext/bc/C/rpc"
fuji = "https://api.avax-test.network/ext/bc/C/rpc"

[fmt]
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config